# SPDX-FileCopyrightText: © 2024 Tenstorrent AI ULC

# SPDX-License-Identifier: Apache-2.0

from .model_op_src_from_another_op import BudaElementWiseBinaryTest
from .model_op_src_from_tm_edge1 import BudaElementWiseBinaryTest
from .model_op_src_from_tm_edge2 import BudaElementWiseBinaryTest
from .model_op_src_from_host import BudaElementWiseBinaryTest
from .model_op_src_from_dram_queue import BudaElementWiseBinaryTest
from .model_op_src_from_dram_queue_prologued import BudaElementWiseBinaryTest
from .model_op_src_const_eval_pass import BudaElementWiseBinaryTest
