from .model_op_src_const_inputs1 import BudaMatmulTest
from .model_op_src_const_inputs2 import BudaMatmulTest
from .model_op_src_from_another_op import BudaMatmulTest
from .model_op_src_from_dram1 import BudaMatmulTest
from .model_op_src_from_dram2 import BudaMatmulTest
from .model_op_src_from_host import BudaMatmulTest
from .model_op_src_from_tm_edge1 import BudaMatmulTest
from .model_op_src_from_tm_edge2 import BudaMatmulTest
