name: "Build artifacts"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      - name: TBD build actions
        run: echo "TBD build actions"
      - name: Sleep 3
        run: echo "Sleep 3"